apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo-cd-demo
  name: argo-cd-demo
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: argo-cd-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo-cd-demo
  name: argo-cd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-cd-demo
  template:
    metadata:
      labels:
        app: argo-cd-demo
    spec:
      containers:
      - image: ghcr.io/tao12345666333/argo-cd-demo/argo-cd-demo:7df55c41572a05f92d759fa4e65f328348dc706b
        name: argo-cd-demo
        ports:
        - containerPort: 8888
